// Generated from packages/mining-core/src/index.js.
// Run `npm run generate:skill`; do not edit this file directly.

export const DATE_OPTIONS = Object.freeze({
  "Past 1 Day": "now 1-d",
  "Past 7 Days": "now 7-d",
  "Past 30 Days": "today 1-m",
  "Past 90 Days": "today 3-m",
  "Past 12 Months": "",
});

export const GEO_OPTIONS = Object.freeze({
  Global: "",
  "United States": "US",
  Japan: "JP",
  "United Kingdom": "GB",
  Germany: "DE",
  France: "FR",
  Canada: "CA",
  Australia: "AU",
  India: "IN",
  China: "CN",
});

export const COMPARISON_KEYWORDS = Object.freeze([
  ["empty", "No comparison"],
  ["weather", "weather · broad reference"],
  ["chatgpt", "chatgpt · strong reference"],
  ["ai tools", "ai tools · medium reference"],
  ["image converter", "image converter · utility reference"],
  ["keyword research", "keyword research · SEO reference"],
]);

export const DEFAULT_ROOT_KEYWORDS = Object.freeze([
  "Translator",
  "Processor",
  "Designer",
  "Compiler",
  "Analyzer",
  "Evaluator",
  "Sender",
  "Receiver",
  "Interpreter",
  "Uploader",
  "Calculator",
  "Generator",
  "Sample",
  "Template",
  "Format",
  "Builder",
  "Scheme",
  "Pattern",
  "Checker",
  "Detector",
  "Scraper",
  "Manager",
  "Example",
  "Explorer",
  "Dashboard",
  "Planner",
  "Tracker",
  "Recorder",
  "Optimizer",
  "Scheduler",
  "Converter",
  "Viewer",
  "Extractor",
  "Convert",
  "Monitor",
  "Notifier",
  "Verifier",
  "Simulator",
  "Assistant",
  "Constructor",
  "Comparator",
  "Navigator",
  "Syncer",
  "Connector",
  "Online",
  "Cataloger",
  "Responder",
  "Downloader",
  "Maker",
  "Creator",
  "Editor",
  "Guide",
]);

export const DEFAULT_SETTINGS = Object.freeze({
  country: "Global",
  timeRange: "Past 30 Days",
  activeLibrary: "custom",
  maxTabs: 1,
  comparisonKeyword: "empty",
  maxDepth: 2,
  maxKeywords: 200,
  maxRelatedPerKeyword: 5,
  semanticThreshold: 0.32,
  settingsSchemaVersion: 4,
  threshold: 20,
});

export function uniqueKeywords(keywords) {
  const seen = new Set();
  const result = [];

  for (const keyword of keywords) {
    const normalized = String(keyword ?? "").trim();
    const key = normalized.toLocaleLowerCase();
    if (!normalized || seen.has(key)) continue;
    seen.add(key);
    result.push(normalized);
  }

  return result;
}

export function normalizeKeywordInput(input) {
  return uniqueKeywords(
    String(input ?? "")
      .replace(/\.html\b/gi, "")
      .replace(/[-_]/g, " ")
      .split(/[;\n\r]+/)
      .map((keyword) => keyword.replace(/\s+/g, " ").trim()),
  );
}

export function validateKeyword(keyword) {
  const normalized = String(keyword ?? "").trim();
  if (!normalized || normalized.length > 100 || normalized.includes(",")) {
    return false;
  }
  return normalized.split(/\s+/).length <= 6;
}

export function comparisonTerms(comparisonKeyword) {
  const value = String(comparisonKeyword ?? "").trim();
  return !value || value === "empty" ? [] : [value];
}

export function keywordsPerTab(comparisonKeyword) {
  return Math.max(1, 5 - comparisonTerms(comparisonKeyword).length);
}

export function buildTrendsUrl(
  keywords,
  {
    timeRange = DEFAULT_SETTINGS.timeRange,
    country = DEFAULT_SETTINGS.country,
  } = {},
) {
  const cleaned = uniqueKeywords(keywords).slice(0, 5);
  if (cleaned.length === 0) {
    throw new Error("At least one keyword is required.");
  }

  const parts = [];
  const date = DATE_OPTIONS[timeRange] ?? "";
  const geo = GEO_OPTIONS[country] ?? "";

  if (date) parts.push(`date=${encodeURIComponent(date)}`);
  if (geo) parts.push(`geo=${encodeURIComponent(geo)}`);
  parts.push(`q=${cleaned.map((keyword) => encodeURIComponent(keyword)).join(",")}`);
  parts.push("hl=en-US");

  return `https://trends.google.com/trends/explore?${parts.join("&")}`;
}

export function buildBatchTrendsUrls(
  keywords,
  comparisonKeyword,
  settings,
  maxTabs,
) {
  const candidates = uniqueKeywords(keywords);
  const baseline = comparisonTerms(comparisonKeyword);
  const perTab = keywordsPerTab(comparisonKeyword);
  const limit = Math.max(1, Math.min(20, Number(maxTabs) || 1));
  const urls = [];
  const used = [];

  for (let index = 0; index < limit; index += 1) {
    const selected = candidates.slice(index * perTab, (index + 1) * perTab);
    if (selected.length === 0) break;
    urls.push(buildTrendsUrl([...baseline, ...selected], settings));
    used.push(...selected);
  }

  return { urls, used };
}

export function stripGoogleJsonPrefix(text) {
  const source = String(text ?? "").trimStart();
  const brace = source.search(/[\[{]/);
  if (brace === -1) throw new Error("Google Trends returned invalid JSON.");
  return JSON.parse(source.slice(brace));
}

export function detectEffectiveKeywords(
  timelineData,
  candidateKeywords,
  threshold,
  { hasReference = true } = {},
) {
  if (!Array.isArray(timelineData) || timelineData.length < 10) return [];

  const values = timelineData.map((point) =>
    Array.isArray(point?.value) ? point.value.map(Number) : [],
  );
  const referenceLast = hasReference
    ? Number(values.at(-1)?.[0]) || 0
    : null;
  const effective = [];

  candidateKeywords.forEach((keyword, candidateIndex) => {
    const columnIndex = candidateIndex + (hasReference ? 1 : 0);
    const series = values.map((row) => Number(row[columnIndex]) || 0);
    if (series.length !== values.length) return;

    const earlyWindowSize = Math.max(3, Math.ceil(series.length * 0.2));
    const early = series.slice(0, earlyWindowSize);
    const recent = series.slice(-3);
    const average = (items) =>
      items.reduce((total, value) => total + value, 0) /
      Math.max(1, items.length);
    const earlyAverage = average(early);
    const recentAverage = average(recent);
    const lastValue = series.at(-1) ?? 0;
    const growthRatio = recentAverage / Math.max(earlyAverage, 1);
    const recentGain = lastValue - (recent[0] ?? 0);
    const materiallyGrowing =
      growthRatio >= 1.5 &&
      recentGain >= Math.max(2, (recent[0] ?? 0) * 0.1);
    const score = hasReference
      ? referenceLast === 0
        ? lastValue > 0
          ? Number.POSITIVE_INFINITY
          : 0
        : (lastValue / referenceLast) * 100
      : lastValue;

    if (materiallyGrowing && score >= Number(threshold)) {
      effective.push(keyword);
    }
  });

  return effective;
}

export function extractRelatedKeywords(
  payloads,
  excludedKeywords = [],
  { limitPerPayload = Number.POSITIVE_INFINITY } = {},
) {
  const excluded = new Set(
    excludedKeywords.map((keyword) => String(keyword).toLocaleLowerCase()),
  );
  const result = [];
  const limit = boundedNumber(
    limitPerPayload,
    Number.POSITIVE_INFINITY,
    1,
    100,
  );

  for (const payload of payloads) {
    const rankedLists = payload?.default?.rankedList;
    if (!Array.isArray(rankedLists)) continue;
    const rising = rankedLists[1]?.rankedKeyword ?? [];
    const top = rankedLists[0]?.rankedKeyword ?? [];
    const selected = rising.length > 0 ? rising : top;
    let added = 0;

    for (const item of selected) {
      if (added >= limit) break;
      const keyword = String(item?.query ?? "").trim();
      const key = keyword.toLocaleLowerCase();
      if (!validateKeyword(keyword) || excluded.has(key)) continue;
      excluded.add(key);
      result.push(keyword);
      added += 1;
    }
  }

  return result;
}

function boundedNumber(value, fallback, minimum, maximum) {
  const number = Number(value);
  if (!Number.isFinite(number)) return fallback;
  return Math.max(minimum, Math.min(maximum, number));
}

function sessionTimestamp(now) {
  const value = Number(now);
  return Number.isFinite(value) ? value : Date.now();
}

/**
 * Create the JSON-serializable source of truth for one Mining run.
 *
 * The returned object deliberately contains no browser, tab, timer, storage, or
 * transport state. Those concerns belong to platform adapters.
 */
export function createMiningSession(
  {
    keywords,
    comparisonKeyword = DEFAULT_SETTINGS.comparisonKeyword,
    timeRange = "Past 7 Days",
    country = DEFAULT_SETTINGS.country,
    maxDepth = DEFAULT_SETTINGS.maxDepth,
    maxKeywords = DEFAULT_SETTINGS.maxKeywords,
    maxRelatedPerKeyword = DEFAULT_SETTINGS.maxRelatedPerKeyword,
    semanticMode = "off",
    semanticThreshold = DEFAULT_SETTINGS.semanticThreshold,
    threshold = DEFAULT_SETTINGS.threshold,
  },
  now = Date.now(),
) {
  const rootKeywords = uniqueKeywords(keywords ?? []);
  const comparison = comparisonTerms(comparisonKeyword).at(0) ?? "empty";

  if (rootKeywords.length === 0) {
    throw new Error("Add at least one seed keyword before starting.");
  }

  const timestamp = sessionTimestamp(now);
  const referenceKeyword =
    comparisonTerms(comparison).at(0) ?? rootKeywords[0];
  const keywordDepths = Object.fromEntries(
    rootKeywords.map((keyword) => [keyword.toLocaleLowerCase(), 0]),
  );
  return {
    schemaVersion: 3,
    status: "running",
    rootKeywords,
    queue: [...rootKeywords],
    keywordDepths,
    relatedKeywords: [],
    effectiveKeywords: [],
    semanticRelevantKeywords: [],
    semanticRejectedKeywords: [],
    semanticScores: {},
    batchesProcessed: 0,
    deepestProcessed: 0,
    processed: 0,
    maxDepth: boundedNumber(maxDepth, 2, 0, 5),
    maxKeywords: boundedNumber(maxKeywords, 200, 1, 2_000),
    maxRelatedPerKeyword: boundedNumber(
      maxRelatedPerKeyword,
      5,
      1,
      25,
    ),
    semanticMode: semanticMode === "local" ? "local" : "off",
    semanticStatus: semanticMode === "local" ? "waiting" : "off",
    semanticThreshold: boundedNumber(
      semanticThreshold,
      DEFAULT_SETTINGS.semanticThreshold,
      0,
      1,
    ),
    semanticError: null,
    threshold: boundedNumber(threshold, 20, 1, 10_000),
    timeRange: DATE_OPTIONS[timeRange] === undefined ? "Past 7 Days" : timeRange,
    country: GEO_OPTIONS[country] === undefined ? "Global" : country,
    comparisonKeyword: comparison,
    referenceKeyword,
    referenceMode: comparison === "empty" ? "seed" : "custom",
    currentBatch: [],
    currentDepth: null,
    batchInFlight: false,
    startedAt: timestamp,
    updatedAt: timestamp,
    lastError: null,
  };
}

export function publicMiningSession(session, now = Date.now()) {
  if (!session) return null;
  return {
    schemaVersion: session.schemaVersion ?? 3,
    status: session.status,
    rootKeywords: [...(session.rootKeywords ?? [])],
    relatedKeywords: [...(session.relatedKeywords ?? [])],
    effectiveKeywords: [...(session.effectiveKeywords ?? [])],
    semanticRelevant:
      session.semanticRelevantKeywords?.length ?? 0,
    semanticRejected:
      session.semanticRejectedKeywords?.length ?? 0,
    semanticScores: { ...(session.semanticScores ?? {}) },
    semanticMode: session.semanticMode ?? "off",
    semanticStatus: session.semanticStatus ?? "off",
    semanticThreshold:
      Number(session.semanticThreshold) ||
      DEFAULT_SETTINGS.semanticThreshold,
    semanticError: session.semanticError ?? null,
    batchesProcessed: Number(session.batchesProcessed) || 0,
    deepestProcessed: Number(session.deepestProcessed) || 0,
    processed: Number(session.processed) || 0,
    maxDepth: Number(session.maxDepth) || 0,
    maxKeywords: Number(session.maxKeywords) || 0,
    threshold: Number(session.threshold) || 0,
    timeRange: session.timeRange,
    country: session.country,
    comparisonKeyword: session.comparisonKeyword,
    referenceKeyword: session.referenceKeyword,
    referenceMode: session.referenceMode,
    currentBatch: [...(session.currentBatch ?? [])],
    currentDepth:
      session.currentDepth != null &&
      Number.isFinite(Number(session.currentDepth))
        ? Number(session.currentDepth)
        : null,
    queued: Array.isArray(session.queue) ? session.queue.length : 0,
    startedAt: session.startedAt,
    updatedAt: sessionTimestamp(now),
    lastError: session.lastError ?? null,
  };
}

export function selectNextMiningBatch(session, now = Date.now()) {
  if (!session || session.status !== "running" || session.batchInFlight) {
    return { session, batch: [], complete: session?.status === "complete" };
  }

  const capacity = session.maxKeywords - session.processed;
  const queue = [...session.queue];
  if (capacity <= 0 || queue.length === 0) {
    return {
      session: {
        ...session,
        status: "complete",
        currentBatch: [],
        batchInFlight: false,
        updatedAt: sessionTimestamp(now),
      },
      batch: [],
      complete: true,
    };
  }

  const firstKeyword = queue[0];
  const firstDepth =
    Number(session.keywordDepths?.[firstKeyword.toLocaleLowerCase()]) || 0;
  const automaticReferenceIsInBatch =
    session.referenceMode === "seed" &&
    firstDepth === 0;
  const perBatch = automaticReferenceIsInBatch ? 5 : 4;
  const batch = [];
  while (
    batch.length < Math.min(perBatch, capacity) &&
    queue.length > 0
  ) {
    const keyword = queue[0];
    const depth =
      Number(session.keywordDepths?.[keyword.toLocaleLowerCase()]) || 0;
    if (depth !== firstDepth) break;
    batch.push(queue.shift());
  }
  return {
    session: {
      ...session,
      queue,
      currentBatch: batch,
      currentDepth: firstDepth,
      batchInFlight: true,
      updatedAt: sessionTimestamp(now),
      lastError: null,
    },
    batch,
    complete: false,
  };
}

export function applyMiningObservation(
  session,
  {
    timelineData,
    relatedPayloads = [],
    allowedRelatedKeywords,
    semanticScores = {},
  },
  now = Date.now(),
) {
  if (!session?.batchInFlight || session.currentBatch.length === 0) {
    throw new Error("No Mining batch is waiting for an observation.");
  }
  if (!Array.isArray(timelineData)) {
    throw new Error("The Mining observation has no timeline data.");
  }

  const referenceOverlapsBatch = session.currentBatch.some(
    (keyword) =>
      keyword.toLocaleLowerCase() ===
      String(session.referenceKeyword).toLocaleLowerCase(),
  );
  const detectedEffective = detectEffectiveKeywords(
    timelineData,
    session.currentBatch,
    session.threshold,
    {
      hasReference:
        Boolean(session.referenceKeyword) &&
        !referenceOverlapsBatch,
    },
  );
  const rootSet = new Set(
    session.rootKeywords.map((keyword) => keyword.toLocaleLowerCase()),
  );
  const effective = detectedEffective.filter(
    (keyword) => !rootSet.has(keyword.toLocaleLowerCase()),
  );
  const effectiveKeywords = uniqueKeywords([
    ...session.effectiveKeywords,
    ...effective,
  ]);
  const related = extractRelatedKeywords(relatedPayloads, [
    session.referenceKeyword,
    ...session.rootKeywords,
    ...session.relatedKeywords,
  ], {
    limitPerPayload: session.maxRelatedPerKeyword,
  });
  const relatedKeywords = uniqueKeywords([
    ...session.relatedKeywords,
    ...related,
  ]);
  const allowedRelatedSet = Array.isArray(allowedRelatedKeywords)
    ? new Set(
        allowedRelatedKeywords.map((keyword) =>
          String(keyword).toLocaleLowerCase(),
        ),
      )
    : null;
  const relevantRelated = allowedRelatedSet
    ? related.filter((keyword) =>
        allowedRelatedSet.has(keyword.toLocaleLowerCase()),
      )
    : related;
  const rejectedRelated = allowedRelatedSet
    ? related.filter(
        (keyword) =>
          !allowedRelatedSet.has(keyword.toLocaleLowerCase()),
      )
    : [];
  const semanticRelevantKeywords = uniqueKeywords([
    ...(session.semanticRelevantKeywords ?? []),
    ...relevantRelated,
  ]);
  const semanticRejectedKeywords = uniqueKeywords([
    ...(session.semanticRejectedKeywords ?? []),
    ...rejectedRelated,
  ]);

  const queued = new Set(
    [
      ...session.rootKeywords,
      ...session.queue,
      ...session.currentBatch,
    ].map((keyword) => keyword.toLocaleLowerCase()),
  );
  const queue = [...session.queue];
  const keywordDepths = { ...(session.keywordDepths ?? {}) };
  const currentDepth = Number(session.currentDepth) || 0;
  const nextDepth = currentDepth + 1;
  const canExpand = currentDepth < session.maxDepth;
  for (const keyword of relevantRelated) {
    const key = keyword.toLocaleLowerCase();
    if (queued.has(key)) continue;
    queued.add(key);
    keywordDepths[key] = nextDepth;
    if (canExpand) queue.push(keyword);
  }

  const processed = session.processed + session.currentBatch.length;
  const complete = processed >= session.maxKeywords || queue.length === 0;
  return {
    session: {
      ...session,
      status: complete ? "complete" : session.status,
      queue,
      keywordDepths,
      relatedKeywords,
      effectiveKeywords,
      semanticRelevantKeywords,
      semanticRejectedKeywords,
      semanticScores: {
        ...(session.semanticScores ?? {}),
        ...semanticScores,
      },
      batchesProcessed: (Number(session.batchesProcessed) || 0) + 1,
      deepestProcessed: Math.max(
        Number(session.deepestProcessed) || 0,
        currentDepth,
      ),
      processed,
      currentBatch: [],
      currentDepth: null,
      batchInFlight: false,
      updatedAt: sessionTimestamp(now),
      lastError: null,
    },
    addedRelated: related,
    addedRelevant: relevantRelated,
    rejectedSemantic: rejectedRelated,
    addedEffective: effective,
    complete,
  };
}

export function setMiningStatus(session, status, now = Date.now()) {
  if (!session) return null;
  if (!["running", "paused", "complete", "error"].includes(status)) {
    throw new Error(`Unsupported Mining status: ${status}`);
  }
  return {
    ...session,
    status,
    updatedAt: sessionTimestamp(now),
  };
}

export function failMiningSession(session, error, now = Date.now()) {
  if (!session) return null;
  return {
    ...session,
    status: "error",
    batchInFlight: false,
    currentBatch: [],
    lastError: error instanceof Error ? error.message : String(error),
    updatedAt: sessionTimestamp(now),
  };
}

export function restoreMiningSession(saved, now = Date.now()) {
  if (!saved || !["running", "paused"].includes(saved.status)) return null;
  const rootKeywords = uniqueKeywords(saved.rootKeywords ?? []);
  const comparison =
    comparisonTerms(saved.comparisonKeyword).at(0) ?? "empty";
  const referenceKeyword =
    saved.referenceKeyword ??
    comparisonTerms(comparison).at(0) ??
    rootKeywords[0];
  const restoredQueue = uniqueKeywords([
    ...(saved.currentBatch ?? []),
    ...(saved.queue ?? []),
  ]);
  const keywordDepths = { ...(saved.keywordDepths ?? {}) };
  for (const keyword of rootKeywords) {
    keywordDepths[keyword.toLocaleLowerCase()] = 0;
  }
  for (const keyword of restoredQueue) {
    const key = keyword.toLocaleLowerCase();
    if (!Number.isFinite(Number(keywordDepths[key]))) {
      keywordDepths[key] = rootKeywords.some(
        (root) => root.toLocaleLowerCase() === key,
      )
        ? 0
        : 1;
    }
  }
  return {
    ...saved,
    schemaVersion: 3,
    status: "paused",
    rootKeywords,
    queue: restoredQueue,
    keywordDepths,
    batchesProcessed: Number(saved.batchesProcessed) || 0,
    deepestProcessed: Number(saved.deepestProcessed) || 0,
    maxDepth: boundedNumber(saved.maxDepth, 2, 0, 5),
    maxRelatedPerKeyword: boundedNumber(
      saved.maxRelatedPerKeyword,
      5,
      1,
      25,
    ),
    semanticRelevantKeywords: uniqueKeywords(
      saved.semanticRelevantKeywords ?? [],
    ),
    semanticRejectedKeywords: uniqueKeywords(
      saved.semanticRejectedKeywords ?? [],
    ),
    semanticScores: { ...(saved.semanticScores ?? {}) },
    semanticMode: saved.semanticMode === "local" ? "local" : "off",
    semanticStatus:
      saved.semanticMode === "local"
        ? "waiting"
        : "off",
    semanticThreshold: boundedNumber(
      saved.semanticThreshold,
      DEFAULT_SETTINGS.semanticThreshold,
      0,
      1,
    ),
    semanticError: null,
    comparisonKeyword: comparison,
    referenceKeyword,
    referenceMode:
      saved.referenceMode ??
      (comparison === "empty" ? "seed" : "custom"),
    currentBatch: [],
    currentDepth: null,
    batchInFlight: false,
    updatedAt: sessionTimestamp(now),
  };
}

const command = process.argv[2] ?? "help";
const options = parseOptions(process.argv.slice(3));

switch (command) {
  case "create": {
    const seeds = options.seed.flatMap((value) => normalizeKeywordInput(value));
    const session = createMiningSession({
      keywords: seeds,
      comparisonKeyword: options.comparison.at(-1) ?? "empty",
      country: options.country.at(-1) ?? "Global",
      maxDepth: options.depth.at(-1) ?? 2,
      timeRange: options.time.at(-1) ?? "Past 30 Days",
      maxKeywords: options.max.at(-1) ?? 200,
      maxRelatedPerKeyword: options.breadth.at(-1) ?? 5,
      threshold: options.threshold.at(-1) ?? 20,
    });
    print(advanceSession(session));
    break;
  }
  case "advance": {
    const input = await readJsonInput(options.input.at(-1));
    const observed = applyMiningObservation(input.session, {
      timelineData: input.timelineData,
      relatedPayloads: input.relatedPayloads ?? [],
      allowedRelatedKeywords: input.allowedRelatedKeywords,
      semanticScores: input.semanticScores ?? {},
    });
    print({
      ...advanceSession(observed.session),
      addedRelated: observed.addedRelated,
      addedRelevant: observed.addedRelevant,
      rejectedSemantic: observed.rejectedSemantic,
      addedEffective: observed.addedEffective,
    });
    break;
  }
  case "restore": {
    const input = await readJsonInput(options.input.at(-1));
    const session = restoreMiningSession(input.session ?? input);
    print({ session, restored: Boolean(session) });
    break;
  }
  case "explain":
    print({
      signal:
        "A candidate's recent average must be at least 1.5x its early average, its latest point must show material recent growth, and its latest relative signal must meet the threshold.",
      caveat:
        "This is a relative Google Trends signal, not search volume, ranking difficulty, traffic, or a guaranteed opportunity.",
      defaultDepth: 2,
      expansionPerKeyword: 5,
      laterBatchLimit: 4,
    });
    break;
  default:
    process.stdout.write(
      [
        "Indie Keyword Finder Mining runner",
        "",
        "create  --seed <keyword> [--comparison <optional-reference>] [--country Global]",
        "        [--time \"Past 30 Days\"] [--depth 2] [--breadth 5]",
        "        [--max 200] [--threshold 20]",
        "advance --input <observation.json>  # omit --input to read stdin",
        "restore --input <session.json>      # omit --input to read stdin",
        "explain",
        "",
      ].join("\n"),
    );
}

function advanceSession(session) {
  if (!session || session.status !== "running") {
    return {
      session,
      complete: session?.status === "complete",
      nextBatch: [],
      nextUrl: null,
    };
  }
  const selected = selectNextMiningBatch(session);
  return {
    session: selected.session,
    complete: selected.complete,
    nextBatch: selected.batch,
    nextUrl:
      selected.batch.length > 0
        ? buildTrendsUrl(
            [
              selected.session.referenceKeyword,
              ...selected.batch,
            ],
            selected.session,
          )
        : null,
  };
}

function parseOptions(args) {
  const result = {
    breadth: [],
    comparison: [],
    country: [],
    depth: [],
    input: [],
    max: [],
    seed: [],
    threshold: [],
    time: [],
  };
  for (let index = 0; index < args.length; index += 1) {
    const token = args[index];
    if (!token.startsWith("--")) continue;
    const name = token.slice(2);
    if (!(name in result)) throw new Error(`Unknown option: --${name}`);
    const value = args[index + 1];
    if (value === undefined || value.startsWith("--")) {
      throw new Error(`Missing value for --${name}`);
    }
    result[name].push(value);
    index += 1;
  }
  return result;
}

async function readJsonInput(path) {
  const { readFile } = await import("node:fs/promises");
  const text = await readFile(path || 0, "utf8");
  return JSON.parse(text);
}

function print(value) {
  process.stdout.write(`${JSON.stringify(value, null, 2)}\n`);
}
